In [1]:
import numpy as np

In [2]:
minha_lista = 1, 2, 3 # cria uma lista

In [3]:
minha_lista


(1, 2, 3)

In [4]:
np.array(minha_lista) # cria um array da lista

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # cria um array em formato de matriz

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange (0, 10) # Cria um array de 10 numeros começando do 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange (0, 10 , 2) # cria um array onde ele vai indo em 2 e 2 sendo o limite o 10

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3) # array com 3 zeros

array([0., 0., 0.])

In [10]:
arr = np.zeros(3)

In [11]:
arr

array([0., 0., 0.])

In [12]:
arr = np.zeros((5, 5)) # um array em formato de matriz de 0 de 5x5

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3, 3)) # uma matriz de 3x3 de numeros 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4) # uma matriz com a diagonal principal com numeros 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.linspace(0, 10, 2) # array igualmente espaçado entre 0 e 10, sendo 2 numeros

array([ 0., 10.])

In [20]:
np.linspace(0, 10, 3) # array igualmente espaçado entre 0 e 10, sendo 3 numeros

array([ 0.,  5., 10.])

In [23]:
np.random.rand(5) * 100 # 5 numeros random de até 100

array([23.09794636, 48.42196982, 95.04578861, 37.26248072, 87.03356808])

In [22]:
np.random.rand(5, 4, 3) # Gera um array 3D (5x4x3) com valores aleatórios entre 0 e 1

array([[[0.67299448, 0.25356867, 0.93737889],
        [0.052675  , 0.41343357, 0.36018319],
        [0.67401856, 0.69103999, 0.05305867],
        [0.31158709, 0.17673174, 0.24562191]],

       [[0.51869248, 0.75871392, 0.48286555],
        [0.72436576, 0.68540784, 0.04394234],
        [0.36447753, 0.28942652, 0.12532493],
        [0.51973494, 0.4649026 , 0.32261511]],

       [[0.20940251, 0.75743897, 0.03729829],
        [0.9690617 , 0.85418184, 0.23141083],
        [0.60008581, 0.16173112, 0.63140143],
        [0.6592714 , 0.2660228 , 0.22693858]],

       [[0.17087908, 0.30842734, 0.91007272],
        [0.14931337, 0.05789019, 0.35303361],
        [0.51340003, 0.05024693, 0.75059982],
        [0.87741785, 0.07307022, 0.80667613]],

       [[0.68642636, 0.72449549, 0.87930402],
        [0.75392796, 0.7183772 , 0.0656251 ],
        [0.84266429, 0.07414238, 0.4914833 ],
        [0.7355549 , 0.47128421, 0.87044116]]])

In [24]:
np.random.rand(4) # 4 nuemros random de 0 a 1

array([0.02400501, 0.10858437, 0.94469594, 0.89476184])

In [25]:
np.random.randn(4) # Gera um array com 4 valores aleatórios seguindo uma distribuição normal padrão

array([ 0.81203851,  0.45041696,  1.11375165, -0.57014926])

In [26]:
np.random.randint(0, 100, 10) # gera 10 nuemros aleatórios entre o intervalo de 0 a 99

array([20, 28, 78, 56, 59, 45, 37, 44, 84, 28])

In [27]:
np.random.rand(5) * 100 # 5 numeros aleatórios entre 0 e 100

array([40.4798133 , 66.82785117, 12.94768369, 83.62717401, 56.77644107])

In [28]:
np.round(np.random.rand(5), 0) #  Gera 5 números aleatórios entre 0 e 1 e arredonda para 0 casas decimais

array([0., 0., 1., 0., 1.])

In [29]:
np.round(np.random.rand(5) * 100, 0) #  Gera 5 números aleatórios entre 0 e 100 e arredonda para 0 casas decimais

array([11., 45.,  1., 55.,  0.])

In [30]:
arr = np.random.rand(25) # um array de numeros random entre 0 e 1


In [31]:
arr

array([0.78944744, 0.92815543, 0.23008991, 0.31380931, 0.97889885,
       0.21663364, 0.1495714 , 0.82393426, 0.28877556, 0.02520462,
       0.88972867, 0.38706532, 0.39999642, 0.2855474 , 0.56444727,
       0.28890034, 0.79286674, 0.69682464, 0.78002081, 0.0271919 ,
       0.23489297, 0.00670319, 0.738311  , 0.50425139, 0.60903979])

In [37]:
arr.reshape((5, 5))

array([[0.39265544, 0.1263744 , 0.90788995, 0.69550912, 0.56025822],
       [0.0973678 , 0.91486565, 0.69601876, 0.21176454, 0.26538792],
       [0.22394016, 0.42090031, 0.5791962 , 0.33418668, 0.02450032],
       [0.42048044, 0.8257862 , 0.45775391, 0.08449992, 0.32722693],
       [0.47327297, 0.56286675, 0.19138398, 0.9519195 , 0.04493932]])

In [32]:
arr = arr.reshape((5, 5)) # Reorganiza o array para o formato 5x5

In [40]:
arr

array([[0.39265544, 0.1263744 , 0.90788995, 0.69550912, 0.56025822],
       [0.0973678 , 0.91486565, 0.69601876, 0.21176454, 0.26538792],
       [0.22394016, 0.42090031, 0.5791962 , 0.33418668, 0.02450032],
       [0.42048044, 0.8257862 , 0.45775391, 0.08449992, 0.32722693],
       [0.47327297, 0.56286675, 0.19138398, 0.9519195 , 0.04493932]])

In [34]:
arr.shape # tamanho da linha e coluna do array (no caso 5x5)

(5, 5)

In [35]:
arr.max() # valor maximo dentro do array

0.9788988456611507

In [36]:
arr.min() # Valor minimo dentro do array

0.006703185023958502

In [37]:
arr.argmax() # posição do valor max

4

In [38]:
arr.argmin() # posicão do valor min

21