In [1]:
import numpy as np

In [5]:
minha_lista = 1, 2, 3

In [6]:
minha_lista


(1, 2, 3)

In [7]:
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange (0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange (0, 10 , 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
arr = np.zeros(3)

In [15]:
arr

array([0., 0., 0.])

In [16]:
arr = np.zeros((5, 5))

In [17]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [25]:
np.random.rand(5) * 100

array([26.03746297, 71.07513585, 75.11632123, 12.74891051, 97.21464733])

In [27]:
np.random.rand(5, 4, 3)

array([[[0.20010972, 0.06673847, 0.78152222],
        [0.3284909 , 0.02818927, 0.10475347],
        [0.01539953, 0.94539917, 0.51588199],
        [0.42753884, 0.58274644, 0.71323988]],

       [[0.98292644, 0.47446405, 0.22170018],
        [0.55097092, 0.54030116, 0.1440862 ],
        [0.78983822, 0.62236138, 0.27871951],
        [0.85569693, 0.31816658, 0.57817612]],

       [[0.28462099, 0.07000626, 0.63140228],
        [0.56563122, 0.63104294, 0.68202184],
        [0.25115518, 0.88880579, 0.15275169],
        [0.34191231, 0.06140172, 0.91361897]],

       [[0.06308861, 0.94636296, 0.39572522],
        [0.17517774, 0.81880816, 0.06761947],
        [0.618615  , 0.03168131, 0.71167082],
        [0.49724984, 0.15109741, 0.37907163]],

       [[0.21693875, 0.27013344, 0.31353384],
        [0.46105858, 0.81716695, 0.30604359],
        [0.6755041 , 0.50243161, 0.53972713],
        [0.06925355, 0.14349568, 0.4646131 ]]])

In [29]:
np.random.rand(4)

array([0.73270853, 0.610071  , 0.2596268 , 0.79361699])

In [30]:
np.random.randn(4)

array([-0.53431149, -0.27624699,  2.91712632,  0.34349988])

In [31]:
np.random.randint(0, 100, 10)

array([65, 16, 53, 35, 61, 25, 80, 31, 93, 33])

In [32]:
np.random.rand(5) * 100

array([76.30469903, 66.26063696, 74.01089213, 83.296299  , 54.4117021 ])

In [33]:
np.round(np.random.rand(5), 0)

array([0., 1., 1., 0., 1.])

In [34]:
np.round(np.random.rand(5) * 100, 0)

array([72., 62., 44., 15., 88.])

In [35]:
arr = np.random.rand(25)


In [36]:
arr

array([0.39265544, 0.1263744 , 0.90788995, 0.69550912, 0.56025822,
       0.0973678 , 0.91486565, 0.69601876, 0.21176454, 0.26538792,
       0.22394016, 0.42090031, 0.5791962 , 0.33418668, 0.02450032,
       0.42048044, 0.8257862 , 0.45775391, 0.08449992, 0.32722693,
       0.47327297, 0.56286675, 0.19138398, 0.9519195 , 0.04493932])

In [37]:
arr.reshape((5, 5))

array([[0.39265544, 0.1263744 , 0.90788995, 0.69550912, 0.56025822],
       [0.0973678 , 0.91486565, 0.69601876, 0.21176454, 0.26538792],
       [0.22394016, 0.42090031, 0.5791962 , 0.33418668, 0.02450032],
       [0.42048044, 0.8257862 , 0.45775391, 0.08449992, 0.32722693],
       [0.47327297, 0.56286675, 0.19138398, 0.9519195 , 0.04493932]])

In [39]:
arr = arr.reshape((5, 5))

In [40]:
arr

array([[0.39265544, 0.1263744 , 0.90788995, 0.69550912, 0.56025822],
       [0.0973678 , 0.91486565, 0.69601876, 0.21176454, 0.26538792],
       [0.22394016, 0.42090031, 0.5791962 , 0.33418668, 0.02450032],
       [0.42048044, 0.8257862 , 0.45775391, 0.08449992, 0.32722693],
       [0.47327297, 0.56286675, 0.19138398, 0.9519195 , 0.04493932]])

In [41]:
arr.shape

(5, 5)

In [43]:
arr.max()

0.9519195040512641

In [44]:
arr.min()

0.024500324129057005

In [45]:
arr.argmax()

23

In [46]:
arr.argmin()

14