In [ ]:
# biblioteca
import pandas as pd

In [ ]:
pd.__version__ # versão

'2.2.2'

In [ ]:
#previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000


In [ ]:
# classe
y = pd.read_csv('/content/saidas_breast.csv')
y

,0
0,0
1,0
2,0
3,0
4,0
...,...
564,0
565,0
566,0
567,0


In [ ]:
# biblioteca
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
sklearn.__version__ # versão

'1.6.1'

In [ ]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.25) # 25 % dos dados para testar e os 75% para treinar

In [ ]:
x_treinamento.shape, y_treinamento.shape # (registros)

((426, 30), (426, 1))

In [ ]:
x_teste.shape, y_teste.shape # (registros)

((143, 30), (143, 1))

In [ ]:
# biblioteca
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [ ]:
tf.__version__ # versão

'2.20.0'

In [ ]:
(30 + 1) / 2 # calculo de neuronios da camada oculta

15.5

In [ ]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'), # foi acrescentado depois
    tf.keras.layers.Dense(units = 1, activation= 'sigmoid')
]) # rede neural para duas camadas oculta

In [ ]:
30 * 16, 496 - 480 # Bias

(480, 16)

In [ ]:
496 + 17 # parametros totais

513

In [ ]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5) # Criando o otimizador

In [ ]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) # definindo os parametros

In [ ]:
426 / 10 # calculo do batch size

42.6

In [ ]:
rede_neural.fit(x_treinamento, y_treinamento, batch_size = 10, epochs = 100) # processamento

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5657 - loss: 1.3611   
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7113 - loss: 0.6450 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7582 - loss: 0.5148 
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7512 - loss: 0.7316 
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.4008 
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7535 - loss: 0.5007 
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7441 - loss: 0.8310
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.4399 
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 0.4063 
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7770 - loss: 0.7261
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy

In [ ]:
x_teste

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
466,13.14,20.74,85.98,536.9,0.08675,0.10890,0.108500,0.035100,0.1562,0.06020,...,14.80,25.46,100.90,689.1,0.13510,0.35490,0.450400,0.118100,0.2563,0.08174
178,13.01,22.22,82.01,526.4,0.06251,0.01938,0.001595,0.001852,0.1395,0.05234,...,14.00,29.02,88.18,608.8,0.08125,0.03432,0.007977,0.009259,0.2295,0.05843
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,235.0000,0.07389,...,15.49,30.73,106.20,739.3,0.17030,0.54010,539.000000,206.000000,0.4378,0.10720
192,9.72,18.22,60.73,288.1,0.06950,0.02344,0.000000,0.000000,0.1653,0.06447,...,9968.00,20.83,62.25,303.8,0.07117,0.02729,0.000000,0.000000,0.1909,0.06559
227,15.00,15.51,97.45,684.5,0.08371,0.10960,0.065050,0.037800,0.1881,0.05907,...,16.41,19.31,114.20,808.2,0.11360,0.36270,0.340200,0.137900,0.2954,0.08362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,12.07,13.44,77.83,445.2,0.11000,0.09009,0.037810,0.027980,0.1657,0.06608,...,13.45,15.77,86.92,549.9,0.15210,0.16320,0.162200,0.073930,0.2781,0.08052
387,13.88,16.16,88.37,596.6,0.07026,0.04831,0.020450,0.008507,0.1607,0.05474,...,15.51,19.97,99.66,745.3,0.08484,0.12330,0.109100,0.045370,0.2542,0.06623
62,14.25,22.15,96.42,645.7,0.10490,0.20080,0.213500,0.086530,0.1949,0.07292,...,17.67,29.51,119.10,959.5,164.00000,0.62470,0.692200,0.178500,0.2844,0.11320
210,20.58,22.14,134.70,1290.0,0.09090,0.13480,164.000000,0.095610,0.1765,0.05024,...,23.24,27.84,158.30,1656.0,0.11780,292.00000,0.386100,192.000000,0.2909,0.05865


In [ ]:
pesos0 = rede_neural.layers[0].get_weights() # pesos da camada de entrada
pesos0

[array([[-3.08604807e-01, -3.75434682e-02, -4.80825305e-02,
         -5.83254918e-03, -2.83310950e-01,  4.21559773e-02,
         -1.34338886e-01,  1.55548856e-01,  3.07330549e-01,
         -4.89479691e-01, -1.03492402e-02, -8.87950230e-03,
          1.31174743e-01,  4.53588739e-02, -1.70881316e-01,
         -1.37943283e-01],
        [-3.72955084e-01, -6.94444701e-02, -6.83702156e-03,
          3.86419147e-02, -2.87078887e-01,  4.80894037e-02,
         -1.10905722e-01,  1.60220772e-01,  3.37799460e-01,
         -4.60955679e-01,  4.60562930e-02,  6.67046905e-02,
          1.84454367e-01,  5.27654700e-02, -2.96522379e-01,
         -3.20365205e-02],
        [-1.92496255e-01,  2.09088568e-02, -9.12423283e-02,
         -3.91594805e-02, -2.32207924e-01,  9.82415229e-02,
         -1.58943459e-02,  5.02562597e-02,  1.06277332e-01,
          3.73892859e-02, -3.65322977e-02, -7.89622217e-02,
          2.76937246e-01,  3.95947546e-02,  1.34325167e-02,
         -1.06769232e-02],
        [-1.0064512

In [ ]:
len(pesos0) # quantidade de pesos

2

In [ ]:
len(pesos0[1])

16

In [ ]:
len(pesos0[0])

30

In [ ]:
pesos1 = rede_neural.layers[1].get_weights() # pesos da camada oculta
pesos1

[array([[-6.14234544e-02,  1.58725940e-02, -1.42249931e-03,
          3.52781313e-03,  5.54751009e-02, -3.38237062e-02,
          1.15486778e-01, -5.45807071e-02, -9.03424546e-02,
         -6.02095295e-03, -3.82355675e-02, -7.67848939e-02,
          2.33979262e-02, -5.73372617e-02, -2.64882166e-02,
         -3.53372050e-03],
        [-7.70112276e-02,  2.96810679e-02, -3.51449591e-03,
          3.19352038e-02,  9.32483189e-03,  3.77662457e-03,
         -5.95279224e-02,  9.11732689e-02,  3.10351141e-02,
         -8.61131921e-02,  3.58207300e-02, -6.52336702e-02,
         -5.25863515e-03, -2.93688346e-02, -5.52046746e-02,
          5.89531139e-02],
        [ 8.89401808e-02,  5.18943630e-02, -4.86278813e-03,
          1.21942073e-01,  2.42243949e-02,  3.36102815e-03,
         -2.39374191e-02,  6.59721345e-02, -3.26327933e-03,
          2.40596719e-02, -2.57432442e-02,  8.45527798e-02,
         -4.54519270e-03,  4.75485325e-02,  3.88599597e-02,
         -4.40599136e-02],
        [-5.8154117

In [ ]:
pesos2 = rede_neural.layers[2].get_weights() # pesos da camada oculta
pesos2

[array([[ 0.10561626],
        [ 0.14754725],
        [-0.63052094],
        [-0.22328536],
        [ 0.11032628],
        [-0.34376284],
        [ 0.15472522],
        [ 0.14547817],
        [-0.46976137],
        [ 0.21503893],
        [-0.12410948],
        [ 0.10507302],
        [-0.48283798],
        [ 0.05689038],
        [-0.281772  ],
        [ 0.17218693]], dtype=float32),
 array([0.30275223], dtype=float32)]

In [ ]:
previsoes = rede_neural.predict(x_teste) # celula da variavel de previsoes
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step


In [ ]:
previsoes

array([[ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [ ]:
y_teste

,0
466,1
178,1
8,0
192,1
227,1
...,...
529,1
387,1
62,0
210,0


In [ ]:
# importação
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
accuracy_score(y_teste, previsoes) # acuracia

0.8461538461538461

In [ ]:
confusion_matrix(y_teste, previsoes) # matriz de acertos por classes

array([[50,  7],
       [15, 71]])

In [ ]:
50 + 71, 15 + 7 # acertos, erros

(121, 22)

In [ ]:
121 / 143, 22 / 143 # taxa de acerto, erro

(0.8461538461538461, 0.15384615384615385)

In [ ]:
rede_neural.evaluate(x_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7483 - loss: 0.8892  


[0.8891670107841492, 0.748251736164093]