In [2]:
# bibliotecas
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [3]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '2.0.2', '2.20.0', '1.6.1')

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [7]:
base = pd.read_csv('/content/iris.csv') # leitura do csv dos dados
base

,sepal length,sepal width,petal length,petal width,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [8]:
X = base.iloc[:, 0:4] # todas as linhas e pegas as colunas 0,1,2 e 3
X

,sepal length,sepal width,petal length,petal width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [9]:
y = base.iloc[:, 4].values # mostras os valores das linhas apenas da coluna 4
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [10]:
label_encoder = LabelEncoder() # transforma as variaveis string em numeros(0,1,2)
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
np.shape(y) # quantidade

(150,)

In [13]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25) # separa os dados em treinamento e teste

In [14]:
X_treinamento.shape, X_teste.shape # quantidade de registros para treinamento e teste de X

((112, 4), (38, 4))

In [15]:
y_treinamento.shape, y_teste.shape # quantidade de registros para treinamento e teste de y

((112, 3), (38, 3))

In [17]:
(4 + 3) / 2 # quantidade de neuronios na camada oculta

3.5

In [18]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(input_shape=(4,)),
    tf.keras.layers.Dense(units=4, activation='relu'), # camada oculta
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax') # camada de saida, softmax pq tem o uso de mais de 2 classes
]) # rede neural onde cria uma sequencia de camada

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


In [21]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
rede_neural.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy']) # compilar a rede

In [23]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size=10, epochs=1000) # treinar a rede

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - categorical_accuracy: 0.3214 - loss: 1.3577
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3214 - loss: 1.2737 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3214 - loss: 1.1998 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3304 - loss: 1.1228 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5000 - loss: 1.0418 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6875 - loss: 0.9987 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5804 - loss: 0.9723 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.4375 - loss: 0.9533 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4018 - loss: 0.9452 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3929 - loss: 0.9373 
Epoch 11/

In [24]:
rede_neural.evaluate(X_teste, y_teste) # avaliar a rede

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - categorical_accuracy: 0.9474 - loss: 0.1692 


[0.16918234527111053, 0.9473684430122375]

In [25]:
previsoes = rede_neural.predict(X_teste) # previsoes utilizando a variavel X_teste
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [3.4940506e-03, 7.6799947e-01, 2.2850657e-01],
       [9.9999946e-01, 4.7842269e-07, 5.1851284e-20],
       [9.9999958e-01, 3.5169529e-07, 5.4901212e-20],
       [2.3408022e-03, 9.5748818e-01, 4.0170960e-02],
       [9.9999136e-01, 8.6285772e-06, 2.1887014e-16],
       [1.0327865e-04, 9.9989480e-01, 1.9432957e-06],
       [4.1679834e-04, 1.7348332e-02, 9.8223484e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [2.6754097e-03, 3.1199947e-01, 6.8532503e-01],
       [5.6332734e-04, 9.9902642e-01, 4.1028709e-04],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [8.8141547e-05, 9.9991065e-01, 1.1787794e-06],
       [3.3937037e-04, 1.2812268e-02, 9.8684841e-01],
       [9.9999923e-01, 6.7259231e-07, 1.3401722e-19],
       [5.4586207e-04, 9.9908274e-01, 3.7144471e-04],
       [3.3554616e-03, 5.0916994e-01, 4.8747450e-01],
       [2.2172919e-03, 2.239

In [26]:
previsoes = previsoes > 0.5 # facilitar o entendimento dos valores dividindo em True e False
print(previsoes)

[[False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]]


In [33]:
y_teste2 = [int(np.argmax(t)) for t in y_teste]
print(y_teste2) # representação no formato original das classes

[2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0]


In [34]:
previsoes2 = [int(np.argmax(t)) for t in previsoes]
print(previsoes2) # representação no formato original das classes

[2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 1, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0]


In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_teste2, previsoes2) # acuracia do modelo

0.9473684210526315

In [40]:
# 0 setosa, 1 versicolor, 2 virginica

In [39]:
confusion_matrix(y_teste2, previsoes2)

array([[14,  0,  0],
       [ 0,  9,  1],
       [ 0,  1, 13]])