In [ ]:
import torch

## Multiplicação

In [ ]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) # é criado um tensor 2D

In [ ]:
print(x.shape)# com duas linhas e quatro colunas

torch.Size([2, 4])


In [ ]:
x*10 # multiplica cada elemento por 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

## Soma

In [ ]:
x.add(10) # adiciona 10 em cada elemento

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

## Remodelar
Existem várias maneiras de remodelar um tensor.

## 1) Visualizar

In [ ]:
# 1-) Visualizar
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
x.shape

torch.Size([2, 4])

In [ ]:
x.view(4,2) # é remodelado os valores das linhas e colunas para 4x2

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

## Ao remodelar o tensor, precisamos ter em mente que o número de elementos em seu interior deve permanecer o mesmo; por exemplo, se tínhamos 8 elementos no total, as possíveis formas para as quais ele pode ser convertido também devem conter 8 elementos.

In [ ]:
x.view(8,1) # 8 linhas e 1 coluna

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

## 2) Espremer
No squeeze, fornecemos o índice do eixo que queremos remover, o qual possui apenas um item nessa dimensão.

In [ ]:
a = torch.ones(2,1,10) # é criado um tensor em 2x1x10 e comprimimos a primeira dimensão

In [ ]:
#Este é um tensor composto por duas pilhas, cada uma com uma linha e 10 colunas, totalizando 20 elementos
a


tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.squeeze(1)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 1, 10])
Este é o formato depois de apertar torch.Size([2, 10])


## Como você pode ver, removemos o primeiro índice do eixo, que contém apenas um item. Se o eixo tiver mais de um item, ele não será removido.

In [ ]:
a = torch.ones(2,2,10)
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.squeeze(1)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 2, 10])
Este é o formato depois de apertar torch.Size([2, 2, 10])


## 3) soltar
É o exato oposto de squeeze: em vez de remover, estamos adicionando uma dimensão ao nosso tensor.

In [ ]:
a = torch.ones(2,3)
print(f"Este é o formato antes de apertar {a.shape}")
squeezed = a.unsqueeze(2)
print(f"Este é o formato depois de apertar {squeezed.shape}")

Este é o formato antes de apertar torch.Size([2, 3])
Este é o formato depois de apertar torch.Size([2, 3, 1])


## Indexação [None]: uma abordagem muito comum

In [ ]:
a = torch.ones(2,3)

In [ ]:
#Adicionar "none" criaria automaticamente uma dimensão fictícia no eixo especificado:
print(a[None].shape)# eixo fictício no índice 0
print(a[:,None].shape)#eixo fictício no índice 1
print(a[:,:,None].shape)#eixo fictício no índice 2


torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


## Em visão computacional, tenha em mente que o formato do tensor seria:
Para tensor 1D(número total de elementos)

Para tensor 2D(linhas e colunas)

Para tensor 3D(número de canais, linhas e colunas)

Para tensor 4D(tamanho do lote, número de canais, linhas e colunas)