Arrays

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [2]:
arr_arange = np.arange(0, 10)  # cria um array de 0 a 10

In [3]:
arr_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Arrays especiais

In [4]:
np.zeros(5) # cria um array contendo x(5) zeros

array([0., 0., 0., 0., 0.])

In [5]:
np.ones((3,3)) # Cria 3 arrays contendo x(3) numeros 1.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.eye(4) # cria uma matriz de 4 x 4, onde a matriz principal tem numero 1 e o resto zero(matriz identidade)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.linspace(0, 1, 5) # Cria um array onde inicia no valor 0 e vai até o 1, dividido em 5 partes iguais

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Valores aleatórios

In [8]:
np.random.rand(3) # Cria um array aleatório contendo x(3) numeros aleatórios entre 0 e 1

array([0.53487058, 0.74017288, 0.22450513])

In [9]:
np.random.randn(3) # Cria um array aleatório contendo x(3) numeros que tendem a ficar perto de 0

array([ 0.31276711, -0.4008803 , -0.72543232])

Mudando a forma do array

In [13]:
arr = np.arange(1, 13) # Cria um array que vai do 1 ao 12

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr.reshape(3, 4) # ele mudou a forma para 3 linha e 4 colunas

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Máximo, mínimo e índices

In [16]:
arr = np.array([10, 25, 5, 7])

In [17]:
np.max(arr) # Pegou o valor maior

25

In [18]:
np.min(arr) # Pegou o valor menor

5

In [21]:
np.argmax(arr) # é "1", pois o indice do maior numero é 1 [0, 1, 2, 3]

1

In [22]:
np.argmin(arr) # é "2", pois o indice do menor numero é 1 [0, 1, 2, 3]

2

Indexação e fatiamento

In [23]:
arr = np.arange(0, 10)
arr[3]

3

In [24]:
arr[2:6] # pega os valores apartir do valor 2 até o 5

array([2, 3, 4, 5])

In [25]:
arr[5:] = 99 # apartir do valor 5 ele troca os antigos valores por 99

In [26]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99])

Operações matemática

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [28]:
a + b # soma

array([5, 7, 9])

In [29]:
a * b # multiplica

array([ 4, 10, 18])

In [30]:
a - b # subtrai

array([-3, -3, -3])

In [31]:
 a / b # dividi

array([0.25, 0.4 , 0.5 ])

In [32]:
a ** b # calcula a exponenciação

array([  1,  32, 729])

In [33]:
np.sqrt(a) # raiz

array([1.        , 1.41421356, 1.73205081])

In [34]:
np.mean(a) # média

2.0

In [35]:
np.std(a) # desvio padrão

0.816496580927726