In [1]:
try:
  %tensorflow_version 2.0
except Exception:
  pass

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
2.20.0


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
sentences = [
    'I like eggs and ham.',
    'I love chocolate and bunnies',
    'I hate onions'
]

In [6]:
MAX_VOCAB_SIZE = 20000 # tamanho máximo
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE) # cria um token com o maximo
tokenizer.fit_on_texts(sentences) # apaga os espaços
sequences = tokenizer.texts_to_sequences(sentences) # converte

In [7]:
print(sequences)

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]


In [8]:
tokenizer.word_index

{'i': 1,
 'and': 2,
 'like': 3,
 'eggs': 4,
 'ham': 5,
 'love': 6,
 'chocolate': 7,
 'bunnies': 8,
 'hate': 9,
 'onions': 10}

In [10]:
data = pad_sequences(sequences) # padding das sequências
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [11]:
MAX_SEQUENCE_LENGTH = 5 # limita em 5 palavras
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [12]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post') # padding no final
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 1  9 10  0  0]]


In [13]:
data = pad_sequences(sequences, maxlen=4) # tamanho da sequência reduzido
print(data)

[[ 3  4  2  5]
 [ 6  7  2  8]
 [ 0  1  9 10]]


In [14]:
data = pad_sequences(sequences, maxlen=4, truncating='post')
print(data)

[[ 1  3  4  2]
 [ 1  6  7  2]
 [ 0  1  9 10]]
